title: "Your Awesome Eurorack Project"
email: "your-email@example.com"
description: "A site dedicated to my Eurorack modular synth builds."
theme: minima
plugins:
  - jekyll-feed

url: "https://yourusername.github.io"
baseurl: ""
permalink: pretty # Clean URLs (e.g., /modules/vco/)

header_pages:
  - about.md
  - modules.md